// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "FSS 技术团队",
            "email": "dev@fss-mining.io"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account/assets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回当前用户的交易区余额、挖矿区余额及有效算力。有效算力规则：min(max(质押量, 100), 2000)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "资产"
                ],
                "summary": "查询用户资产",
                "responses": {
                    "200": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ResponseErr"
                        }
                    }
                }
            }
        },
        "/admin/mining/config/activate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将指定月份的挖矿配置设置为当前激活配置（同时停用其他月份配置），激活后系统使用该配置进行每日结算",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员"
                ],
                "summary": "[管理] 激活某月挖矿配置",
                "parameters": [
                    {
                        "description": "激活信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ActivatePeriodReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "月份不存在",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ResponseErr"
                        }
                    }
                }
            }
        },
        "/admin/mining/config/init": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据月份、月编号（用于复利计算）、初始流通量和增长率生成该月的挖矿参数（每日产出、月产出等），生成后需调用 activate 接口激活",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员"
                ],
                "summary": "[管理] 初始化某月挖矿配置",
                "parameters": [
                    {
                        "description": "配置信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.InitPeriodReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 配置已存在",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ResponseErr"
                        }
                    }
                }
            }
        },
        "/admin/mining/configs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回当前激活的挖矿周期配置详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员"
                ],
                "summary": "[管理] 查询所有挖矿周期配置",
                "responses": {
                    "200": {
                        "description": "配置列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_handler.ResponseOK"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_handler.PeriodConfigInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/mining/settle": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "对指定日期重新执行静态奖励结算，已完成的批次会被跳过（幂等保护），用于修复漏算或异常场景",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员"
                ],
                "summary": "[管理] 手动触发补算",
                "parameters": [
                    {
                        "description": "结算日期",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ManualSettleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "日期格式错误 / 结算失败",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ResponseErr"
                        }
                    }
                }
            }
        },
        "/mining/network": {
            "get": {
                "description": "返回全网质押规模、有效算力、参与用户数、昨日产出及当前挖矿周期配置，无需登录可访问",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "挖矿"
                ],
                "summary": "全网挖矿看板（公开）",
                "responses": {
                    "200": {
                        "description": "全网看板数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_handler.ResponseOK"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_handler.NetworkBoardRespData"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/mining/period": {
            "get": {
                "description": "返回当前激活的月度挖矿配置，包含每日产出、月产出、静态/动态比例、质押门槛等",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "挖矿"
                ],
                "summary": "查询当前挖矿周期配置（公开）",
                "responses": {
                    "200": {
                        "description": "配置不存在",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ResponseErr"
                        }
                    }
                }
            }
        },
        "/mining/rewards": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分页查询当前用户的每日挖矿奖励明细，包含静态奖励、动态奖励、当日有效算力及全网算力",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "挖矿"
                ],
                "summary": "查询个人挖矿奖励记录",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码（默认1）",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量（默认20，最大100）",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ResponseErr"
                        }
                    }
                }
            }
        },
        "/transfer/in": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将交易区资产划转到挖矿区。划转后资金冻结，24小时后的次日00:00正式生效参与挖矿。支持幂等键防止重复提交。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "划转"
                ],
                "summary": "从交易区转入挖矿区",
                "parameters": [
                    {
                        "description": "划转信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.TransferInReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "余额不足 / 低于最低门槛",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ResponseErr"
                        }
                    }
                }
            }
        },
        "/transfer/out": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将挖矿区资产划转回交易区。资金冻结，24小时后到账。支持幂等键防止重复提交。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "划转"
                ],
                "summary": "从挖矿区转出到交易区",
                "parameters": [
                    {
                        "description": "划转信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.TransferOutReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "余额不足",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ResponseErr"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "使用用户名和密码登录，返回 JWT Token（有效期72小时）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ResponseErr"
                        }
                    }
                }
            }
        },
        "/user/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回当前登录用户的基本信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取当前用户信息",
                "responses": {
                    "200": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ResponseErr"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "注册新用户，系统自动创建交易区和挖矿区账户，并生成唯一邀请码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 用户名已存在",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ResponseErr"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_handler.AccountDetail": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "string",
                    "example": "1000.00000000"
                },
                "balance": {
                    "type": "string",
                    "example": "1000.00000000"
                },
                "frozen": {
                    "type": "string",
                    "example": "0.00000000"
                }
            }
        },
        "internal_handler.ActivatePeriodReq": {
            "type": "object",
            "required": [
                "month"
            ],
            "properties": {
                "month": {
                    "type": "string",
                    "example": "2024-01"
                }
            }
        },
        "internal_handler.AssetsRespData": {
            "type": "object",
            "properties": {
                "mining": {
                    "$ref": "#/definitions/internal_handler.MiningAccountDetail"
                },
                "mining_rules": {
                    "$ref": "#/definitions/internal_handler.MiningRules"
                },
                "trade": {
                    "$ref": "#/definitions/internal_handler.AccountDetail"
                }
            }
        },
        "internal_handler.BatchInfo": {
            "type": "object",
            "properties": {
                "actual_paid": {
                    "type": "string",
                    "example": "16499.98765432"
                },
                "dynamic_pool": {
                    "type": "string",
                    "example": "16500.00000000"
                },
                "static_pool": {
                    "type": "string",
                    "example": "16500.00000000"
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                },
                "total_output": {
                    "type": "string",
                    "example": "33000.00000000"
                },
                "valid_users": {
                    "type": "integer",
                    "example": 1500
                }
            }
        },
        "internal_handler.InitPeriodReq": {
            "type": "object",
            "required": [
                "growth_rate",
                "initial_circulation",
                "month",
                "month_number"
            ],
            "properties": {
                "growth_rate": {
                    "type": "string",
                    "example": "0.1"
                },
                "initial_circulation": {
                    "type": "string",
                    "example": "10000000"
                },
                "month": {
                    "type": "string",
                    "example": "2024-01"
                },
                "month_number": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                }
            }
        },
        "internal_handler.LoginReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "username": {
                    "type": "string",
                    "example": "alice"
                }
            }
        },
        "internal_handler.LoginRespData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user": {
                    "$ref": "#/definitions/internal_handler.UserInfo"
                }
            }
        },
        "internal_handler.ManualSettleReq": {
            "type": "object",
            "required": [
                "date"
            ],
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2024-01-01"
                }
            }
        },
        "internal_handler.MiningAccountDetail": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "string",
                    "example": "500.00000000"
                },
                "balance": {
                    "type": "string",
                    "example": "500.00000000"
                },
                "effective_power": {
                    "type": "string",
                    "example": "500.00000000"
                },
                "frozen": {
                    "type": "string",
                    "example": "0.00000000"
                },
                "is_valid_miner": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_handler.MiningRules": {
            "type": "object",
            "properties": {
                "max_stake": {
                    "type": "number",
                    "example": 2000
                },
                "min_stake": {
                    "type": "number",
                    "example": 100
                }
            }
        },
        "internal_handler.NetworkBoardRespData": {
            "type": "object",
            "properties": {
                "current_config": {
                    "$ref": "#/definitions/internal_handler.PeriodConfigInfo"
                },
                "network_stats": {
                    "$ref": "#/definitions/internal_handler.NetworkStatsData"
                },
                "yesterday_batch": {
                    "$ref": "#/definitions/internal_handler.BatchInfo"
                },
                "yesterday_date": {
                    "type": "string",
                    "example": "2024-01-01"
                }
            }
        },
        "internal_handler.NetworkStatsData": {
            "type": "object",
            "properties": {
                "total_effective": {
                    "type": "string",
                    "example": "3000000.00000000"
                },
                "total_stake": {
                    "type": "string",
                    "example": "5000000.00000000"
                },
                "valid_users": {
                    "type": "integer",
                    "example": 1500
                }
            }
        },
        "internal_handler.PeriodConfigInfo": {
            "type": "object",
            "properties": {
                "daily_output": {
                    "type": "string",
                    "example": "33333.33333333"
                },
                "dynamic_ratio": {
                    "type": "string",
                    "example": "0.5000"
                },
                "max_stake": {
                    "type": "string",
                    "example": "2000.00000000"
                },
                "min_stake": {
                    "type": "string",
                    "example": "100.00000000"
                },
                "monthly_output": {
                    "type": "string",
                    "example": "1000000.00000000"
                },
                "period_month": {
                    "type": "string",
                    "example": "2024-01"
                },
                "static_ratio": {
                    "type": "string",
                    "example": "0.5000"
                }
            }
        },
        "internal_handler.RegisterReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "alice@example.com"
                },
                "invite_code": {
                    "type": "string",
                    "example": "a1b2c3d4"
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 6,
                    "example": "password123"
                },
                "phone": {
                    "type": "string",
                    "example": "13800138000"
                },
                "username": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3,
                    "example": "alice"
                }
            }
        },
        "internal_handler.RegisterRespData": {
            "type": "object",
            "properties": {
                "invite_code": {
                    "type": "string",
                    "example": "a1b2c3d4"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "type": "string",
                    "example": "alice"
                }
            }
        },
        "internal_handler.ResponseErr": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 10001
                },
                "message": {
                    "type": "string",
                    "example": "请求参数错误"
                }
            }
        },
        "internal_handler.ResponseOK": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "成功"
                }
            }
        },
        "internal_handler.RewardsRespData": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handler.SettlementItem"
                    }
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "size": {
                    "type": "integer",
                    "example": 20
                },
                "total": {
                    "type": "integer",
                    "example": 30
                },
                "total_reward": {
                    "type": "string",
                    "example": "36.98765432"
                }
            }
        },
        "internal_handler.SettlementItem": {
            "type": "object",
            "properties": {
                "dynamic_reward": {
                    "type": "string",
                    "example": "0.00000000"
                },
                "effective_power": {
                    "type": "string",
                    "example": "500.00000000"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "network_power": {
                    "type": "string",
                    "example": "100000.00000000"
                },
                "settle_date": {
                    "type": "string",
                    "example": "2024-01-01"
                },
                "static_reward": {
                    "type": "string",
                    "example": "1.23456789"
                },
                "status": {
                    "type": "string",
                    "example": "paid"
                },
                "total_reward": {
                    "type": "string",
                    "example": "1.23456789"
                }
            }
        },
        "internal_handler.TransferInReq": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "200.00"
                },
                "idempotent_key": {
                    "type": "string",
                    "example": "my-unique-key-001"
                }
            }
        },
        "internal_handler.TransferOutReq": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "100.00"
                },
                "idempotent_key": {
                    "type": "string",
                    "example": "my-unique-key-002"
                }
            }
        },
        "internal_handler.TransferRespData": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "200.00000000"
                },
                "effective_at": {
                    "type": "string",
                    "example": "2024-01-02T00:00:00+08:00"
                },
                "status": {
                    "type": "string",
                    "example": "locking"
                },
                "transfer_id": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "internal_handler.UserInfo": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "alice@example.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "invite_code": {
                    "type": "string",
                    "example": "a1b2c3d4"
                },
                "phone": {
                    "type": "string",
                    "example": "13800138000"
                },
                "role": {
                    "type": "string",
                    "example": "user"
                },
                "username": {
                    "type": "string",
                    "example": "alice"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "格式：Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8888",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "FSS 挖矿系统 API",
	Description:      "FSS 代币挖矿系统后端接口文档。支持用户注册登录、资产查询、划转（交易区⇄挖矿区）、挖矿奖励查询、全网看板及管理员操作。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
